//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGBDProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class bibliothequeEntities : DbContext
    {
        public bibliothequeEntities()
            : base("name=bibliothequeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<book> books { get; set; }
        public virtual DbSet<exemplar> exemplars { get; set; }
        public virtual DbSet<librarian> librarians { get; set; }
        public virtual DbSet<user> users { get; set; }
    
        public virtual int QuantityIncrease(string book_id)
        {
            var book_idParameter = book_id != null ?
                new ObjectParameter("book_id", book_id) :
                new ObjectParameter("book_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("QuantityIncrease", book_idParameter);
        }
    }
}
