//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGBDProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exemplar
    {
        public string barCode { get; set; }
        public Nullable<System.DateTime> returnDate { get; set; }
        public Nullable<System.DateTime> takeoffDate { get; set; }
    
        public virtual book book { get; set; }
    }
}
