//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGBDProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string user_id { get; set; }
        public string username { get; set; }
        public string usersurname { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
    }
}
